sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 987789qw
  # alioss:
  #   endpoint: oss-cn-beijing.aliyuncs.com
  #   access-key-id: TAI5t7mFgB3RgPLai8v1StEL
  #   access-key-secret: u5WXuERnzBjvoYOORJaWejHy0gCA3m
  #   bucket-name: domye
  redis:
    host: localhost
    port: 6379
    password: 987789qw
    database: 0
